### ISSUE TITLE
Error building matplotlib docs with default value api_usage = 'unused'

### ISSUE THREAD

**Issue by StefRe** [sphinx-gallery/sphinx-gallery#1024]
matplotlib's `conf.py` doesn't specify `api_usage`. The current default value of `unused` (51cd69c71) leads to the following error (shown with `SPHINXOPTS=-W --keep-going -vv`). No errors for `api_usage = False`.

```
Traceback (most recent call last):
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\events.py", line 94, in emit
    results.append(listener.handler(self.app, *args))
  File "c:\daten\python\sphinx-gallery\sphinx_gallery\gen_gallery.py", line 717, in write_api_entries
    app.config.sphinx_gallery_conf['api_entries'][what].add(name)
KeyError: 'exception'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\cmd\build.py", line 279, in build_main
    app.build(args.force_all, filenames)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\application.py", line 350, in build
    self.builder.build_update()
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\builders\__init__.py", line 302, in build_update
    self.build(to_build,
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\builders\__init__.py", line 318, in build
    updated_docnames = set(self.read())
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\builders\__init__.py", line 425, in read
    self._read_serial(docnames)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\builders\__init__.py", line 446, in _read_serial
    self.read_doc(docname)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\builders\__init__.py", line 502, in read_doc
    publisher.publish()
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\core.py", line 217, in publish
    self.document = self.reader.read(self.source, self.parser,
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\io.py", line 104, in read
    self.parse()
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\readers\__init__.py", line 78, in parse
    self.parser.parse(self.input, document)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\parsers.py", line 78, in parse
    self.statemachine.run(inputlines, document, inliner=self.inliner)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\parsers\rst\states.py", line 170, in run
    results = StateMachineWS.run(self, input_lines, input_offset,
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\parsers\rst\states.py", line 3008, in text
    self.section(title.lstrip(), source, style, lineno + 1, messages)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\parsers\rst\states.py", line 327, in section
    self.new_subsection(title, lineno, messages)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\parsers\rst\states.py", line 393, in new_subsection
    newabsoffset = self.nested_parse(
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\parsers\rst\states.py", line 281, in nested_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\parsers\rst\states.py", line 2344, in explicit_markup
    self.explicit_list(blank_finish)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\parsers\rst\states.py", line 2369, in explicit_list
    newline_offset, blank_finish = self.nested_list_parse(
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\parsers\rst\states.py", line 318, in nested_list_parse
    state_machine.run(block, input_offset, memo=self.memo,
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\parsers\rst\states.py", line 196, in run
    results = StateMachineWS.run(self, input_lines, input_offset)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\statemachine.py", line 239, in run
    context, next_state, result = self.check_line(
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\statemachine.py", line 451, in check_line
    return method(match, context, next_state)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\parsers\rst\states.py", line 2647, in explicit_markup
    nodelist, blank_finish = self.explicit_construct(match)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\parsers\rst\states.py", line 2354, in explicit_construct
    return method(self, expmatch)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\parsers\rst\states.py", line 2096, in directive
    return self.run_directive(
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\docutils\parsers\rst\states.py", line 2146, in run_directive
    result = directive_instance.run()
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\ext\autodoc\directive.py", line 148, in run
    documenter.generate(more_content=self.content)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 954, in generate
    self.document_members(all_members)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 830, in document_members
    documenter.generate(
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 1798, in generate
    return super().generate(more_content=more_content,
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 951, in generate
    self.add_content(more_content)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 1784, in add_content
    super().add_content(more_content)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 602, in add_content
    for i, line in enumerate(self.process_doc(docstrings)):
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\ext\autodoc\__init__.py", line 547, in process_doc
    self.env.app.emit('autodoc-process-docstring',
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\application.py", line 461, in emit
    return self.events.emit(event, *args, allowed_exceptions=allowed_exceptions)
  File "C:\programs\mambaforge\envs\mpl-dev\lib\site-packages\sphinx\events.py", line 105, in emit
    raise ExtensionError(__("Handler %r for event %r threw an exception") %
sphinx.errors.ExtensionError: Handler <function write_api_entries at 0x0000023AD2B33EB0> for event 'autodoc-process-docstring' threw an exception (exception: 'exception')

Extension error (sphinx_gallery.gen_gallery):
Handler <function write_api_entries at 0x0000023AD2B33EB0> for event 'autodoc-process-docstring' threw an exception (exception: 'exception')
```

**Comment by larsoner** [comment]
@alexrockhill any ideas?

In the meantime maybe we should change the default to make it not run at all to make it opt-in. Don't want to break people's builds...

**Comment by alexrockhill** [comment]
This is a quick fix, sorry I didn't get to it sooner
