### ISSUE TITLE
BUG: API usage fails when plotting disabled

### ISSUE THREAD

**Issue by larsoner** [sphinx-gallery/sphinx-gallery#1200]
At least in the MNE-Python docs if I do:
```
"show_api_usage": "unused",
```
and run `make html-noplot` (which sets `plot_gallery=False`) I get:
```
writing output... 
building [html]: targets for 90 source files that are out of date
updating environment: [new config] 951 added, 0 changed, 0 removed
reading sources... [ 99%] sg_api_usage
Traceback (most recent call last):
  File "/home/larsoner/python/virtualenvs/base/lib/python3.11/site-packages/docutils/io.py", line 364, in __init__
    self.source = open(source_path, mode,
                  ^^^^^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: '/home/larsoner/python/mne-python/doc/sg_api_usage.rst'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/larsoner/python/sphinx/sphinx/cmd/build.py", line 338, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/larsoner/python/sphinx/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/home/larsoner/python/sphinx/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/home/larsoner/python/sphinx/sphinx/builders/__init__.py", line 313, in build
    updated_docnames = set(self.read())
                           ^^^^^^^^^^^
  File "/home/larsoner/python/sphinx/sphinx/builders/__init__.py", line 420, in read
    self._read_serial(docnames)
  File "/home/larsoner/python/sphinx/sphinx/builders/__init__.py", line 441, in _read_serial
    self.read_doc(docname)
  File "/home/larsoner/python/sphinx/sphinx/builders/__init__.py", line 497, in read_doc
    publisher.set_source(source_path=filename)
  File "/home/larsoner/python/virtualenvs/base/lib/python3.11/site-packages/docutils/core.py", line 187, in set_source
    self.source = self.source_class(
                  ^^^^^^^^^^^^^^^^^^
  File "/home/larsoner/python/sphinx/sphinx/io.py", line 157, in __init__
    super().__init__(*args, **kwargs)
  File "/home/larsoner/python/virtualenvs/base/lib/python3.11/site-packages/docutils/io.py", line 368, in __init__
    raise InputError(error.errno, error.strerror, source_path)
docutils.io.InputError: [Errno 2] No such file or directory: '/home/larsoner/python/mne-python/doc/sg_api_usage.rst'

Exception occurred:
  File "/home/larsoner/python/virtualenvs/base/lib/python3.11/site-packages/docutils/io.py", line 368, in __init__
    raise InputError(error.errno, error.strerror, source_path)
docutils.io.InputError: [Errno 2] No such file or directory: '/home/larsoner/python/mne-python/doc/sg_api_usage.rst'
```
@alexrockhill can you look?

**Comment by larsoner** [comment]
actually I think the fix should be simple, I'll open a quick PR

**Comment by larsoner** [comment]
Actually I *think* this was some weird misconfiguration bug at my end, closing!
