### ISSUE TITLE
Build error for epub

### ISSUE THREAD

**Issue by MuellerSeb** [sphinx-gallery/sphinx-gallery#1285]
Hey there,

recently I run into problems building my documentation on RTD, i.e. when building epub.

I get the following error on the first rst file generated by sphinx-gallery:
```
WARNING: unknown node type: <imgsgnode: >
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/sphinx/cmd/build.py", line 298, in build_main
    app.build(args.force_all, args.filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/sphinx/application.py", line 355, in build
    self.builder.build_update()
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 293, in build_update
    self.build(to_build,
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 363, in build
    self.write(docnames, list(updated_docnames), method)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 571, in write
    self._write_serial(sorted(docnames))
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/sphinx/builders/__init__.py", line 581, in _write_serial
    self.write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/sphinx/builders/_epub_base.py", line 372, in write_doc
    super().write_doc(docname, doctree)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/sphinx/builders/html/__init__.py", line 649, in write_doc
    self.docwriter.write(doctree, destination)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/docutils/writers/__init__.py", line 80, in write
    self.translate()
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/sphinx/writers/html.py", line 36, in translate
    self.document.walkabout(visitor)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/docutils/nodes.py", line 186, in walkabout
    if child.walkabout(visitor):
       ^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/docutils/nodes.py", line 199, in walkabout
    visitor.dispatch_departure(self)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/sphinx/util/docutils.py", line 602, in dispatch_departure
    super().dispatch_departure(node)
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/docutils/nodes.py", line 2019, in dispatch_departure
    return method(node)
           ^^^^^^^^^^^^
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/docutils/nodes.py", line 2041, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: imgsgnode
Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/gstools/envs/latest/lib/python3.11/site-packages/docutils/nodes.py", line 2041, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.html5.HTML5Translator'> departing unknown node type: imgsgnode
The full traceback has been saved in /tmp/sphinx-err-e6t0lg1c.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```

But it was working in the past. I can't determine the point where it broke, but it seems to be related to this: https://sphinx-gallery.github.io/dev/gen_modules/sphinx_gallery.directives.html#sphinx_gallery.directives.imagesg_addnode

I will probably disable epub for now, but maybe there is a better solution.

**Comment by MuellerSeb** [comment]
For reference:
- Log of last successful build: https://readthedocs.org/projects/gstools/builds/21027834/
- Log of first failed build: https://readthedocs.org/projects/gstools/builds/22443975/

**Comment by lucyleeow** [comment]
Odd because image-sg stuff has not been touched for a while. In 0.14 I did some lint/clean up: #1169 (I did delete some unused functions in `directives.py` but I don't think this would be the problem)

Are you sure they both have the same sphinx version?

Last successful, from your link
```
Collecting sphinx<2
  Downloading Sphinx-1.8.6-py2.py3-none-any.whl (3.1 MB)
```
First failed:
```
Collecting sphinx
  Downloading sphinx-7.2.6-py3-none-any.whl.metadata (5.9 kB)
```

**Comment by MuellerSeb** [comment]
In the stage
```
python -m pip install --upgrade --upgrade-strategy eager --no-cache-dir .[doc]
```
They both installed sphinx 5.3

It seems, looking at the old epubs, that the images were missing either way, but it didn't trigger an error:
https://geostat-framework.readthedocs.io/_/downloads/gstools/en/v1.5.0/epub/

**Comment by lucyleeow** [comment]
> It seems, looking at the old epubs, that the images were missing either way, but it didn't trigger an error:

That makes more sense. We've only implemented for html and latex:

https://github.com/sphinx-gallery/sphinx-gallery/blob/e22fc20463055199dee565db3c21c34c9d195c6e/sphinx_gallery/directives.py#L352-L353

We do technically only support html and don't really test other builders.

The error could be due to #1151, which was added in 0.14

Do you think we should not trigger an error in this case?

**Comment by larsoner** [comment]
It would be nice if we could just use default `img` processing for other builders (after removing the `srcset` option or whatever). Not sure if that would be easy though.
