### ISSUE TITLE
Test failures on Fedora rawhide

### ISSUE THREAD

**Issue by opoplawski** [sphinx-gallery/sphinx-gallery#170]
While packaging for Fedora, I'm getting:
```
+ nosetests-3.5
/usr/lib64/python3.5/site-packages/matplotlib/font_manager.py:279: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
/usr/lib64/python3.5/site-packages/matplotlib/font_manager.py:279: UserWarning: Matplotlib is building the font cache using fc-list. This may take a moment.
  warnings.warn('Matplotlib is building the font cache using fc-list. This may take a moment.')
...........EE..S...
======================================================================
ERROR: Test that failing examples are only executed until failing block
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/sphinx-gallery-0.1.5/sphinx_gallery/tests/test_gen_rst.py", line 159, in test_fail_example
    gallery_conf['examples_dir'], gallery_conf)
  File "/builddir/build/BUILD/sphinx-gallery-0.1.5/sphinx_gallery/gen_rst.py", line 599, in generate_file_rst
    if md5sum_is_current(example_file):
  File "/builddir/build/BUILD/sphinx-gallery-0.1.5/sphinx_gallery/gen_rst.py", line 290, in md5sum_is_current
    src_md5 = get_md5sum(src_file)
  File "/builddir/build/BUILD/sphinx-gallery-0.1.5/sphinx_gallery/gen_rst.py", line 277, in get_md5sum
    src_content = src_data.read()
  File "/usr/lib64/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 99: ordinal not in range(128)

======================================================================
ERROR: Test if only examples matching pattern are executed
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/usr/lib/python3.5/site-packages/nose/case.py", line 198, in runTest
    self.test(*self.arg)
  File "/builddir/build/BUILD/sphinx-gallery-0.1.5/sphinx_gallery/tests/test_gen_rst.py", line 192, in test_pattern_matching
    gallery_conf['examples_dir'], gallery_conf)
  File "/builddir/build/BUILD/sphinx-gallery-0.1.5/sphinx_gallery/gen_rst.py", line 599, in generate_file_rst
    if md5sum_is_current(example_file):
  File "/builddir/build/BUILD/sphinx-gallery-0.1.5/sphinx_gallery/gen_rst.py", line 290, in md5sum_is_current
    src_md5 = get_md5sum(src_file)
  File "/builddir/build/BUILD/sphinx-gallery-0.1.5/sphinx_gallery/gen_rst.py", line 277, in get_md5sum
    src_content = src_data.read()
  File "/usr/lib64/python3.5/encodings/ascii.py", line 26, in decode
    return codecs.ascii_decode(input, self.errors)[0]
UnicodeDecodeError: 'ascii' codec can't decode byte 0xc3 in position 99: ordinal not in range(128)

Name                               Stmts   Miss  Cover   Missing
----------------------------------------------------------------
sphinx_gallery.py                      4      1    75%   13
sphinx_gallery/backreferences.py      86     19    78%   117-127, 167-180
sphinx_gallery/docs_resolv.py        252    212    16%   17-18, 33-46, 59, 75-88, 93-128, 147-168, 189-217, 222-272, 294-315, 320-409, 414-440
sphinx_gallery/downloads.py           28      9    68%   104-117
sphinx_gallery/gen_gallery.py        114     97    15%   56-61, 70-149, 158-165, 173-213, 219-221, 226-238, 243
sphinx_gallery/gen_rst.py            338    215    36%   38-54, 64-67, 87-88, 91-92, 95-96, 100, 107-109, 167, 174, 180, 246, 265, 321-366, 375-410, 417-441, 446-488, 494-559, 572-577, 600-684
sphinx_gallery/notebook.py            49      0   100%
----------------------------------------------------------------
TOTAL                                871    553    37%
----------------------------------------------------------------------
Ran 19 tests in 0.901s

FAILED (SKIP=1, errors=2)
```

**Comment by lesteve** [comment]
I can reproduce your failures by doing `LC_ALL='C' nosetests`.

**Comment by lesteve** [comment]
@opoplawski it should be fixed in master. Do reopen if this is not the case.

**Comment by opoplawski** [comment]
That did the trick.  Thanks!
