### ISSUE TITLE
Sphinx-gallery in unbuildable state after crash

### ISSUE THREAD

**Issue by GaelVaroquaux** [sphinx-gallery/sphinx-gallery#343]
A project can get in a state where it is impossible to build with sphinx-gallery:
https://readthedocs.org/projects/joblib/builds/6641437/

I think that I've already seen this on my own computer and that it is related to the ".py" file of an example being present in the output dir and not the .ipynb. We could probably fix this with a better check on our side.

**Comment by choldgraf** [comment]
to be clear, this is something that is fixed by cleaning out the "build" directory yeah?

**Comment by lesteve** [comment]
FWIW I can reproduce a similar error by deleting a .ipynb and regenerating the doc. It goes away if I do `make clean`.

This should reproduce the problem:
```
cd doc
make html
rm auto_examples/plot_sys_argv.ipynb
make html
```

```
# Sphinx version: 1.6.6
# Python version: 3.6.4 (CPython)
# Docutils version: 0.14 
# Jinja2 version: 2.10
# Last messages:

# Loaded extensions:
Traceback (most recent call last):
  File "/home/local/lesteve/miniconda3/lib/python3.6/site-packages/sphinx/cmdline.py", line 305, in main
    opts.warningiserror, opts.tags, opts.verbosity, opts.jobs)
  File "/home/local/lesteve/miniconda3/lib/python3.6/site-packages/sphinx/application.py", line 234, in __init__
    self._init_builder()
  File "/home/local/lesteve/miniconda3/lib/python3.6/site-packages/sphinx/application.py", line 312, in _init_builder
    self.emit('builder-inited')
  File "/home/local/lesteve/miniconda3/lib/python3.6/site-packages/sphinx/application.py", line 489, in emit
    return self.events.emit(event, self, *args)
  File "/home/local/lesteve/miniconda3/lib/python3.6/site-packages/sphinx/events.py", line 79, in emit
    results.append(callback(*args))
  File "/home/ROCQ/sed/lesteve/dev/sphinx-gallery/sphinx_gallery/gen_gallery.py", line 255, in generate_gallery_rst
    download_fhindex = generate_zipfiles(gallery_dir)
  File "/home/ROCQ/sed/lesteve/dev/sphinx-gallery/sphinx_gallery/downloads.py", line 118, in generate_zipfiles
    jy_zipfile = python_zip(listdir, gallery_dir, ".ipynb")
  File "/home/ROCQ/sed/lesteve/dev/sphinx-gallery/sphinx_gallery/downloads.py", line 72, in python_zip
    zipf.write(file_src, os.path.relpath(file_src, gallery_path))
  File "/home/local/lesteve/miniconda3/lib/python3.6/zipfile.py", line 1594, in write
    zinfo = ZipInfo.from_file(filename, arcname)
  File "/home/local/lesteve/miniconda3/lib/python3.6/zipfile.py", line 484, in from_file
    st = os.stat(filename)
FileNotFoundError: [Errno 2] No such file or directory: '/home/local/lesteve/dev/sphinx-gallery/doc/auto_examples/plot_sys_argv.ipynb'
```

**Comment by sizmailov** [comment]
Here is another way to face the error. 
1. Point to non-existing thub image in `conf.py`
```python 
sphinx_gallery_conf = {
   ...
   'default_thumb_file': 'non-existing.png'
}
```
2. do `make html`. Build fails with 
```FileNotFoundError: [Errno 2] No such file or directory: 'non-existing.png'```
3. Fix the image path
4. Do `make html`. Build fails with 

```FileNotFoundError: [Errno 2] No such file or directory: ' ... /plot_example.ipynb'```

Workaround: 
`make clean && rm -r source/auto_examples`
