### ISSUE TITLE
fails to build with recent matplotlib

### ISSUE THREAD

**Issue by sandrotosi** [sphinx-gallery/sphinx-gallery#373]
Hello,
when building sphinx-gallery with matplotlib 2.2.2, we got this error:

```
Unexpected failing examples:
/home/morph/deb/build-area/sphinx-gallery-0.1.13/examples/sin_func/plot_sin_black_background.py failed leaving traceback:
Traceback (most recent call last):
  File "/home/morph/deb/build-area/sphinx-gallery-0.1.13/examples/sin_func/plot_sin_black_background.py", line 20, in <module>
    axes = plt.axes((0.1, 0.1, 0.8, 0.8), axisbg=bg_color)
  File "/usr/lib/python2.7/dist-packages/matplotlib/pyplot.py", line 938, in axes
    return gcf().add_axes(rect, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/figure.py", line 1136, in add_axes
    a = projection_class(self, rect, **kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/axes/_base.py", line 539, in __init__
    self.update(kwargs)
  File "/usr/lib/python2.7/dist-packages/matplotlib/artist.py", line 888, in update
    for k, v in props.items()]
  File "/usr/lib/python2.7/dist-packages/matplotlib/artist.py", line 881, in _update_property
    raise AttributeError('Unknown property %s' % k)
AttributeError: Unknown property axisbg
```

https://matplotlib.org/api/api_changes.html says

> The axisbg and axis_bgcolor properties on Axes have been deprecated in favor of facecolor.

**Comment by sandrotosi** [comment]
this patch fixes it

```
From: Sandro Tosi <morph@debian.org>
Date: Thu, 3 May 2018 19:41:31 -0400
Subject: use facecolor instead of axisbg when calling plt.axes

---
 examples/sin_func/plot_sin_black_background.py | 2 +-
 1 file changed, 1 insertion(+), 1 deletion(-)

diff --git a/examples/sin_func/plot_sin_black_background.py b/examples/sin_func/plot_sin_black_background.py
index 8dd11a1..02adb94 100644
--- a/examples/sin_func/plot_sin_black_background.py
+++ b/examples/sin_func/plot_sin_black_background.py
@@ -17,7 +17,7 @@ bg_color = 'black'
 fg_color = 'white'
 
 fig = plt.figure(facecolor=bg_color, edgecolor=fg_color)
-axes = plt.axes((0.1, 0.1, 0.8, 0.8), axisbg=bg_color)
+axes = plt.axes((0.1, 0.1, 0.8, 0.8), facecolor=bg_color)
 axes.xaxis.set_tick_params(color=fg_color, labelcolor=fg_color)
 axes.yaxis.set_tick_params(color=fg_color, labelcolor=fg_color)
 for spine in axes.spines.values():
```

**Comment by Titan-C** [comment]
Hello thank you for your concern. This was fixed in master already with
PR #357. We are still not ready with a release including this patch.
