### ISSUE TITLE
Version 0.3.0 release is broken on pypi

### ISSUE THREAD

**Issue by drdavella** [sphinx-gallery/sphinx-gallery#459]
Just did `pip install sphinx-gallery` in a clean Py37 environment and got this:
```
Collecting sphinx-gallery
  Using cached https://files.pythonhosted.org/packages/a3/7d/45c423ca42790ad53db2d54a23ca9131faa098107074a649f624b2b9ca42/sphinx-gallery-0.3.0.tar.gz
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/6s/st61dq157dnd1nwd56hzy16h000153/T/pip-install-vvepem75/sphinx-gallery/setup.py", line 31, in <module>
        with open('requirements.txt', 'r') as fid:
    FileNotFoundError: [Errno 2] No such file or directory: 'requirements.txt'
```

**Comment by GaelVaroquaux** [comment]
I've cut a new release. This should be fixed. Can you please confirm.

Thanks

**Comment by drdavella** [comment]
Looks good now.

**Comment by GaelVaroquaux** [comment]
Thanks. Closing.
