### ISSUE TITLE
Read the docs is not building anymore

### ISSUE THREAD

**Issue by Titan-C** [sphinx-gallery/sphinx-gallery#58]
The traceback
```
Traceback (most recent call last):
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-gallery/envs/latest/local/lib/python2.7/site-packages/sphinx/cmdline.py", line 245, in main
    app.build(opts.force_all, filenames)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-gallery/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 282, in build
    self.emit('build-finished', None)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-gallery/envs/latest/local/lib/python2.7/site-packages/sphinx/application.py", line 497, in emit
    results.append(callback(self, *args))
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-gallery/envs/latest/local/lib/python2.7/site-packages/sphinx_gallery-0.0.11-py2.7.egg/sphinxgallery/docs_resolv.py", line 432, in embed_code_links
    _embed_code_links(app, gallery_conf, gallery_dir)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-gallery/envs/latest/local/lib/python2.7/site-packages/sphinx_gallery-0.0.11-py2.7.egg/sphinxgallery/docs_resolv.py", line 328, in _embed_code_links
    relative=True)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-gallery/envs/latest/local/lib/python2.7/site-packages/sphinx_gallery-0.0.11-py2.7.egg/sphinxgallery/docs_resolv.py", line 214, in __init__
    sindex = get_data(searchindex_url, gallery_dir)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-gallery/envs/latest/local/lib/python2.7/site-packages/sphinx_gallery-0.0.11-py2.7.egg/sphinxgallery/docs_resolv.py", line 66, in get_data
    data = _get_data(url)
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-gallery/envs/latest/local/lib/python2.7/site-packages/sphinx_gallery-0.0.11-py2.7.egg/sphinxgallery/docs_resolv.py", line 48, in _get_data
    with open(url, 'r') as fid:
IOError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/sphinx-gallery/checkouts/latest/doc/_build/json/searchindex.js'

Exception occurred:
  File "/home/docs/checkouts/readthedocs.org/user_builds/sphinx-gallery/envs/latest/local/lib/python2.7/site-packages/sphinx_gallery-0.0.11-py2.7.egg/sphinxgallery/docs_resolv.py", line 48, in _get_data
    with open(url, 'r') as fid:
IOError: [Errno 2] No such file or directory: '/home/docs/checkouts/readthedocs.org/user_builds/sphinx-gallery/checkouts/latest/doc/_build/json/searchindex.js'
```
In the link embedding step it searches for `searchindex.js` in the `json` folder and not in the `html` folder. It might be a change in sphinx from pip?

**Comment by lesteve** [comment]
Looking at the readthedocs here: https://readthedocs.org/projects/sphinx-gallery/builds/3274914/.

The html build runs fine but then the json build fails. Any idea what the json build is supposed to do?

**Comment by Titan-C** [comment]
I had a look yesterday. It is more a thing of read the docs that I don't find documentation for. It looks like `app.builder.outdir` is sometimes `html` with html files and sometimes `json` with `json` files. I retested in my branch and own build.
https://github.com/Titan-C/sphinx-gallery/commits/refactor_split
to get some debugging messages
but when I renamed searchindex.js to searchindex.json. Read the docs restarted to use the `html` build.
Compare
https://readthedocs.org/projects/sphinx-gallery-local/builds/3278891/
with
https://readthedocs.org/projects/sphinx-gallery-local/builds/3278880/

And the build will crash again.

**Comment by lesteve** [comment]
OK I don't know why this is happening, but it looks that readthedocs now builds in two steps:
* first with the 'readthedocs' builder (i.e. -b readthedocs) whatever this is and this step succeeds in your second link.
* then with the 'json' builder (i.e. -b json). Not sure what this is useful for to be honest. This step fails in your second link.

In your first link I am not sure what was your intent of renaming searchindex.js to searchindex.json. The 'readthedocs' step now fails because it is trying to open searchindex.json whereas the sphinx build generated a searchindex.js ...

**Comment by lesteve** [comment]
I forgot to say I can reproduce the 'json' builder failure locally by running:

```
sphinx-build -T -b json -d _build/doctrees-json -D language=en . _build/json
```

**Comment by Titan-C** [comment]
> In your first link I am not sure what was your intent of renaming
> searchindex.js to searchindex.json. The 'readthedocs' step now fails
> because it is trying to open searchindex.json whereas the sphinx build
> generated a searchindex.js ...

My mistake, I didn't realize read the docs was doing a 2 step
build. First the html then the json. I only read the fail block where it
searched for a file in the wrong place. Then listing the build folder
there is searchindex.json, that's why the rename.

Now that read the docs calls 2 build steps for the html. Although I
don't know the purpose of the json, maybe a quick fix would be to treat
this builder the same as for latex and skip the link embedding step.

**Comment by lesteve** [comment]
Not as simple as I thought, reopening.

There are more builders used, as an example:
https://readthedocs.org/projects/seismicjl/builds/3264550/

has:
* readthedocs
* json
* readthedocssinglehtmllocalmedia
* latex
* epub

At the moment the readthedocs build fails at readthedocssinglehtmllocalmedia ...

and now it fails on the last one

**Comment by Titan-C** [comment]
I have deactivated latex and epub. but https://github.com/Titan-C/sphinx-gallery/commits/refactor_split seems to work now. I list the allowed builders. only html and readthedocs

**Comment by lesteve** [comment]
Where do I get the readthedocs build from your branch ? I can't figure it out I am afraid.

**Comment by Titan-C** [comment]
It's only the last commit. https://github.com/Titan-C/sphinx-gallery/commit/4dc8977eba158108e48ed695805d490887e6e51c

**Comment by lesteve** [comment]
What I am after is the readthedocs build i.e. the equivalent of https://readthedocs.org/projects/sphinx-gallery/builds/ but for your refactor_split branch.

**Comment by Titan-C** [comment]
https://readthedocs.org/projects/sphinx-gallery-local/

**Comment by lesteve** [comment]
OK I used your whitelist of builders approach as a quick-fix. Maybe there is a more elegant solution though.

Also I think it'd be good to understand why readthedocs builds with these sphinx builders:

* readthedocs
* json
* readthedocssinglehtmllocalmedia
