### ISSUE TITLE
Building fails with pickling error

### ISSUE THREAD

**Issue by edublancas** [sphinx-gallery/sphinx-gallery#602]
Hi, I'm trying to build a gallery for a project that uses the multiprocessing module (hence, it needs to use the pickle module), the script defines a few functions that have to be pickled but building the gallery throws the following error (_get is the function that fails to pickle):

```_pickle.PicklingError: Can't pickle <function _get at 0x11cc9c0d0>: attribute lookup _get on __main__ failed```

Full traceback:

```
Exception occurred:
  File "/Users/Edu/miniconda3/envs/ploomber/lib/python3.6/site-packages/sphinx_gallery/gen_gallery.py", line 544, in summarize_failing_examples
    "\n" + "-" * 79)
ValueError: Here is a summary of the problems encountered when running the examples

Unexpected failing examples:
/Users/Edu/dev/ploomber/examples/train-and-predict.py failed leaving traceback:
Traceback (most recent call last):
  File "/Users/Edu/miniconda3/envs/ploomber/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 440, in _memory_usage
    out = func()
  File "/Users/Edu/miniconda3/envs/ploomber/lib/python3.6/site-packages/sphinx_gallery/gen_rst.py", line 425, in __call__
    exec(self.code, self.globals)
  File "/Users/Edu/dev/ploomber/examples/train-and-predict.py", line 124, in <module>
    dag_fit.build()
  File "/Users/Edu/dev/ploomber/src/ploomber/dag.py", line 167, in build
    return self._executor(dag=self, force=force)
  File "/Users/Edu/dev/ploomber/src/ploomber/executors/Serial.py", line 45, in __call__
    raise e
  File "/Users/Edu/dev/ploomber/src/ploomber/executors/Serial.py", line 40, in __call__
    t.build(**kwargs)
  File "/Users/Edu/dev/ploomber/src/ploomber/tasks/Task.py", line 303, in build
    raise e
  File "/Users/Edu/dev/ploomber/src/ploomber/tasks/Task.py", line 293, in build
    self.run()
  File "/Users/Edu/dev/ploomber/src/ploomber/tasks/tasks.py", line 86, in run
    res.get()
  File "/Users/Edu/miniconda3/envs/ploomber/lib/python3.6/multiprocessing/pool.py", line 644, in get
    raise self._value
  File "/Users/Edu/miniconda3/envs/ploomber/lib/python3.6/multiprocessing/pool.py", line 424, in _handle_tasks
    put(task)
  File "/Users/Edu/miniconda3/envs/ploomber/lib/python3.6/multiprocessing/connection.py", line 206, in send
    self._send_bytes(_ForkingPickler.dumps(obj))
  File "/Users/Edu/miniconda3/envs/ploomber/lib/python3.6/multiprocessing/reduction.py", line 51, in dumps
    cls(buf, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <function _get at 0x11cc9c0d0>: attribute lookup _get on __main__ failed
```

The error happens in ```sphinx_gallery/gen_rst.py```, looks like the way sphinx-gallery runs the code makes the function declaration unavailable, that's why pickle fails.

I noticed that if I define the function in a separate file and import it, the build succeeds. But then the example is incomplete since the source code for the function does not appear.

As a workaround: is there any way for sphinx-gallery to build examples so that the source code for both files is shown?

**Comment by larsoner** [comment]
Can you see if any of the ideas here would work for you?

https://stackoverflow.com/questions/8804830/python-multiprocessing-picklingerror-cant-pickle-type-function

**Comment by edublancas** [comment]
Hi @larsmans, thanks for your answer.

The code example works just fine when doing `python example.py`, that´s why I believe it has to do with the way sphinx-gallery executes code. Are there any details I should be aware of?

**Comment by larsoner** [comment]
Maybe the easiest way to proceed is if you make a minimal example `plot_fail.py` file that won't run, then we replicate locally and take a look at SG fixes or script workarounds.

We use `ast` and code compilation to run files, and it's possible we are doing something wrong.

**Comment by edublancas** [comment]
Example:

```python
"""
This example breaks
"""
import pickle


def function():
    pass


pickle.dumps(function)

```

Traceback:

```
WARNING: /Users/Edu/sphinx/examples/plot_test.py failed to execute correctly: Traceback (most recent call last):
  File "/Users/Edu/miniconda3/envs/test/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 440, in _memory_usage
    out = func()
  File "/Users/Edu/miniconda3/envs/test/lib/python3.8/site-packages/sphinx_gallery/gen_rst.py", line 425, in __call__
    exec(self.code, self.globals)
  File "/Users/Edu/sphinx/examples/plot_test.py", line 11, in <module>
    pickle.dumps(function)
_pickle.PicklingError: Can't pickle <function function at 0x11b6aa700>: attribute lookup function on __main__ failed
```

Tested with Sphinx==2.3.1, sphinx-gallery==0.5.0

Attached the complete setup for your convenience.

[sphinx.zip](https://github.com/sphinx-gallery/sphinx-gallery/files/4131560/sphinx.zip)

Thanks!

**Comment by larsoner** [comment]
This would work:
```
"""
Pickling
--------

This example pickles a function.

Because we ``exec()`` code, pickling, inspection, pkgutil, etc. might need
workarounds to function properly.

Let's define a function that we want to pickle:
"""
import pickle
import sys
import imp


func_code = """
def function():
    pass
"""

##############################################################################
# If we try to pickle it, it will fail in Sphinx-gallery:
#
#     >>> pickle.dumps(function)
#
# So instead you can work around it like:

temp_module = imp.new_module("temp_module")
sys.modules["temp_module"] = temp_module
exec(func_code, temp_module.__dict__)

pickle.dumps(temp_module.function)
```
Would this be a suitable workaround for you? If so I'll add it to the SG docs.

**Comment by larsoner** [comment]
... actually before reformatting your code, you can try #604

**Comment by edublancas** [comment]
It works now. Thanks a lot!
