### ISSUE TITLE
Incompatibility with matplotlib 3.4.0 ?

### ISSUE THREAD

**Issue by pllim** [sphinx-gallery/sphinx-gallery#802]
Hello. Great package! We use this package to generate some nice examples for our documentation. Unfortunately, I might have seen an incompatibility between sphinx-gallery 0.8.2 with matplotlib 3.4.0.

```
WARNING: .../examples/coordinates/plot_obs-planning.py failed to execute correctly: Traceback (most recent call last):
  File ".../sphinx_gallery/scrapers.py", line 333, in save_figures
    rst = scraper(block, block_vars, gallery_conf)
  File ".../sphinx_gallery/scrapers.py", line 149, in matplotlib_scraper
    fig.savefig(image_path, **these_kwargs)
  File ".../matplotlib/figure.py", line 2959, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File ".../matplotlib/backend_bases.py", line 2255, in print_figure
    result = print_method(
  File ".../matplotlib/backend_bases.py", line 1669, in wrapper
    return func(*args, **kwargs)
  File ".../matplotlib/backends/backend_agg.py", line 508, in print_png
    FigureCanvasAgg.draw(self)
  File ".../matplotlib/backends/backend_agg.py", line 406, in draw
    self.figure.draw(self.renderer)
  File ".../matplotlib/artist.py", line 74, in draw_wrapper
    result = draw(artist, renderer, *args, **kwargs)
  File ".../matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File ".../matplotlib/figure.py", line 2734, in draw
    mimage._draw_list_compositing_images(
  File ".../matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File ".../matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File ".../matplotlib/_api/deprecation.py", line 431, in wrapper
    return func(*inner_args, **inner_kwargs)
  File ".../matplotlib/axes/_base.py", line 2925, in draw
    mimage._draw_list_compositing_images(renderer, self, artists)
  File ".../matplotlib/image.py", line 132, in _draw_list_compositing_images
    a.draw(renderer)
  File ".../matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File ".../matplotlib/legend.py", line 614, in draw
    self._legend_box.draw(renderer)
  File ".../matplotlib/offsetbox.py", line 368, in draw
    c.draw(renderer)
  File ".../matplotlib/offsetbox.py", line 368, in draw
    c.draw(renderer)
  File ".../matplotlib/offsetbox.py", line 368, in draw
    c.draw(renderer)
  [Previous line repeated 1 more time]
  File ".../matplotlib/offsetbox.py", line 694, in draw
    c.draw(renderer)
  File ".../matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File ".../matplotlib/collections.py", line 1009, in draw
    super().draw(renderer)
  File ".../matplotlib/artist.py", line 51, in draw_wrapper
    return draw(artist, renderer, *args, **kwargs)
  File ".../matplotlib/collections.py", line 380, in draw
    len(facecolors) == 1 and len(edgecolors) == 1 and
TypeError: object of type 'NoneType' has no len()
```

Entire log at https://readthedocs.org/api/v2/build/13353772.txt (https://readthedocs.org/projects/astropy/builds/)

EDIT: Shortened the paths so traceback is more readable.

**Comment by pllim** [comment]
Actually, I could reproduce this without sphinx-gallery. Maybe this is a matplotlib issue after all. Sorry for the noise!
