### ISSUE TITLE
0.10.1: documentation build fails

### ISSUE THREAD

**Issue by kloczek** [sphinx-gallery/sphinx-gallery#976]
First of all currently it is not possible to use straight `sphinx-build` command to build documentation out of source tree
```console
+ /usr/bin/sphinx-build -n -T -b man doc build/sphinx/man
Running Sphinx v5.0.2

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/conf.py", line 20, in <module>
    import sphinx_gallery
ModuleNotFoundError: No module named 'sphinx_gallery'

The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 272, in build_main
    app = Sphinx(args.sourcedir, args.confdir, args.outputdir,
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 202, in __init__
    self.config = Config.read(self.confdir, confoverrides or {}, self.tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 165, in read
    namespace = eval_config_file(filename, tags)
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 356, in eval_config_file
    raise ConfigError(msg % traceback.format_exc()) from exc
sphinx.errors.ConfigError: There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/conf.py", line 20, in <module>
    import sphinx_gallery
ModuleNotFoundError: No module named 'sphinx_gallery'


Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/config.py", line 343, in eval_config_file
    exec(code, namespace)
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/conf.py", line 20, in <module>
    import sphinx_gallery
ModuleNotFoundError: No module named 'sphinx_gallery'
```

This can be fixed by patch like below:
```patch
--- a/doc/conf.py
+++ b/doc/conf.py
@@ -14,6 +14,11 @@

 import sys
 import os
+# If extensions (or modules to document with autodoc) are in another directory,
+# add these directories to sys.path here. If the directory is relative to the
+# documentation root, use os.path.abspath to make it absolute, like shown here.
+sys.path.insert(0, os.path.abspath(".."))
+
 from datetime import date
 import warnings

@@ -21,11 +26,6 @@
 from sphinx_gallery.sorting import FileNameSortKey
 import sphinx_rtd_theme

-# If extensions (or modules to document with autodoc) are in another directory,
-# add these directories to sys.path here. If the directory is relative to the
-# documentation root, use os.path.abspath to make it absolute, like shown here.
-#sys.path.insert(0, os.path.abspath('.'))
-
 # -- General configuration ------------------------------------------------

 # If your documentation needs a minimal Sphinx version, state it here.
```

Than .. on building documentation sphinx fails with call trace
```console
+ /usr/bin/sphinx-build -n -T -b man doc build/sphinx/man
Running Sphinx v5.0.2
making output directory... done
[autosummary] generating autosummary for: advanced.rst, changes.rst, configuration.rst, faq.rst, getting_started.rst, index.rst, maintainers.rst, projects_list.rst, reference.rst, syntax.rst, utils.rst
[autosummary] generating autosummary for: /home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/gen_modules/sphinx_gallery.backreferences.rst, /home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/gen_modules/sphinx_gallery.binder.rst, /home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/gen_modules/sphinx_gallery.directives.rst, /home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/gen_modules/sphinx_gallery.docs_resolv.rst, /home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/gen_modules/sphinx_gallery.downloads.rst, /home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/gen_modules/sphinx_gallery.gen_gallery.rst, /home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/gen_modules/sphinx_gallery.gen_rst.rst, /home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/gen_modules/sphinx_gallery.notebook.rst, /home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/gen_modules/sphinx_gallery.py_source_parser.rst, /home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/gen_modules/sphinx_gallery.scrapers.rst, /home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/gen_modules/sphinx_gallery.sorting.rst, /home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/gen_modules/sphinx_gallery.utils.optipng.rst
loading intersphinx inventory from https://docs.python.org/3/objects.inv...
loading intersphinx inventory from https://numpy.org/doc/stable/objects.inv...
loading intersphinx inventory from https://matplotlib.org/objects.inv...
loading intersphinx inventory from http://docs.enthought.com/mayavi/mayavi/objects.inv...
loading intersphinx inventory from https://scikit-learn.org/stable/objects.inv...
loading intersphinx inventory from https://www.sphinx-doc.org/en/master/objects.inv...
loading intersphinx inventory from https://pandas.pydata.org/pandas-docs/stable/objects.inv...
intersphinx inventory has moved: https://matplotlib.org/objects.inv -> https://matplotlib.org/stable/objects.inv
generating gallery...
WARNING: Please install 'memory_profiler' to enable peak memory measurements.
Using Sphinx-Gallery to convert rst text blocks to markdown for .ipynb files.
findfont: Font family ['STIXGeneral'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXGeneral'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXGeneral'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXNonUnicode'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXNonUnicode'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXNonUnicode'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXSizeOneSym'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXSizeTwoSym'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXSizeThreeSym'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXSizeFourSym'] not found. Falling back to DejaVu Sans.
findfont: Font family ['STIXSizeFiveSym'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmsy10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmr10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmtt10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmmi10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmb10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmss10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['cmex10'] not found. Falling back to DejaVu Sans.
findfont: Font family ['DejaVu Sans Display'] not found. Falling back to DejaVu Sans.
WARNING: /home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/examples/plot_2_seaborn.py failed to execute correctly: Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/examples/plot_2_seaborn.py", line 17, in <module>
    import seaborn as sns
ModuleNotFoundError: No module named 'seaborn'

WARNING: /home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/examples/plot_3_capture_repr.py failed to execute correctly: Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/examples/plot_3_capture_repr.py", line 64, in <module>
    import statsmodels.iolib.table
ModuleNotFoundError: No module named 'statsmodels'

generating gallery for auto_examples... [100%] plot_9_plotly.py
/home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/examples/no_output/plot_raise.py failed to execute correctly: Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/examples/no_output/plot_raise.py", line 27, in <module>
    iae
NameError: name 'iae' is not defined

/home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/examples/no_output/plot_syntaxerror.py failed to execute correctly: Traceback (most recent call last):
  File "/home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/examples/no_output/plot_syntaxerror.py", line 13
    Invalid Python code
            ^
SyntaxError: invalid syntax


generating gallery for tutorials... [100%] plot_parse.py
computation time summary:
    - ../examples/plot_8_animations.py:            5.24 sec   0.0 MB
    - ../examples/plot_4b_provide_thumbnail.py:    0.99 sec   0.0 MB
    - ../examples/plot_6_function_identifier.py:   0.74 sec   0.0 MB
    - ../examples/plot_9_plotly.py:                0.66 sec   0.0 MB
    - ../examples/plot_4_choose_thumbnail.py:      0.64 sec   0.0 MB
    - ../examples/plot_1_exp.py:                   0.64 sec   0.0 MB
    - ../examples/plot_5_unicode_everywhere.py:    0.60 sec   0.0 MB
    - ../examples/plot_0_sin.py:                   0.56 sec   0.0 MB
    - ../examples/no_output/plot_raise.py:         0.46 sec   0.0 MB
    - ../examples/plot_3_capture_repr.py:          0.16 sec   0.0 MB
    - ../examples/plot_2_seaborn.py:               0.00 sec   0.0 MB
    - ../examples/no_output/plot_strings.py:       0.00 sec   0.0 MB
    - ../tutorials/plot_parse.py:                  0.00 sec   0.0 MB
    - ../examples/plot_7_sys_argv.py:              0.00 sec   0.0 MB
    - ../examples/no_output/plot_syntaxerror.py:   0.00 sec   0.0 MB
    - ../examples/local_module.py:                 0.00 sec   0.0 MB
    - ../examples/no_output/just_code.py:          0.00 sec   0.0 MB
building [mo]: targets for 0 po files that are out of date
building [man]: all manpages
updating environment: [new config] 45 added, 0 changed, 0 removed
reading sources... [100%] utils
/home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/index.rst:71: WARNING: toctree contains reference to nonexisting document 'auto_mayavi_examples/index'
looking for now-outdated files... none found
pickling environment... done
checking consistency... done
writing... python-sphinx-gallery.3 { getting_started syntax configuration projects_list advanced faq utils auto_examples/index auto_examples/local_module auto_examples/plot_0_sin auto_examples/plot_1_exp auto_examples/plot_2_seaborn auto_examples/plot_3_capture_repr auto_examples/plot_4_choose_thumbnail auto_examples/plot_4b_provide_thumbnail auto_examples/plot_5_unicode_everywhere auto_examples/plot_6_function_identifier auto_examples/plot_7_sys_argv auto_examples/plot_8_animations auto_examples/plot_9_plotly auto_examples/no_output/just_code auto_examples/no_output/plot_raise auto_examples/no_output/plot_strings auto_examples/no_output/plot_syntaxerror tutorials/index tutorials/plot_parse reference gen_modules/sphinx_gallery.gen_gallery gen_modules/sphinx_gallery.backreferences gen_modules/sphinx_gallery.gen_rst gen_modules/sphinx_gallery.scrapers gen_modules/sphinx_gallery.py_source_parser gen_modules/sphinx_gallery.docs_resolv gen_modules/sphinx_gallery.notebook gen_modules/sphinx_gallery.downloads gen_modules/sphinx_gallery.sorting gen_modules/sphinx_gallery.binder gen_modules/sphinx_gallery.directives gen_modules/sphinx_gallery.utils.optipng changes } /home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/configuration.rst:1191: WARNING: undefined label: matplotlib:matplotlib-rcparams
/home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/doc/auto_examples/plot_0_sin.rst:: WARNING: unknown node type: <imgsgnode: >
failed

Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 329, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 285, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 352, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 517, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 98, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 31, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 8 more times]
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 240, in walkabout
    visitor.dispatch_departure(self)
  File "/usr/lib/python3.8/site-packages/sphinx/util/docutils.py", line 546, in dispatch_departure
    super().dispatch_departure(node)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 2034, in dispatch_departure
    return method(node)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 2056, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.manpage.ManualPageTranslator'> departing unknown node type: imgsgnode

Exception occurred:
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 2056, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.manpage.ManualPageTranslator'> departing unknown node type: imgsgnode
The full traceback has been saved in /tmp/sphinx-err-hqdc9_ja.log, if you want to report the issue to the developers.
Please also report this if it was a user error, so that a better error message can be provided next time.
A bug report can be filed in the tracker at <https://github.com/sphinx-doc/sphinx/issues>. Thanks!
```
```console
[tkloczko@devel-g2v SOURCES]$ cat /tmp/sphinx-err-hqdc9_ja.log
# Sphinx version: 5.0.2
# Python version: 3.8.13 (CPython)
# Docutils version: 0.17.1 release
# Jinja2 version: 3.1.1
# Last messages:
#   gen_modules/sphinx_gallery.docs_resolv
#   gen_modules/sphinx_gallery.notebook
#   gen_modules/sphinx_gallery.downloads
#   gen_modules/sphinx_gallery.sorting
#   gen_modules/sphinx_gallery.binder
#   gen_modules/sphinx_gallery.directives
#   gen_modules/sphinx_gallery.utils.optipng
#   changes
#   }
#   failed
# Loaded extensions:
#   sphinx.ext.mathjax (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/mathjax.py
#   sphinxcontrib.applehelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/applehelp/__init__.py
#   sphinxcontrib.devhelp (1.0.2) from /usr/lib/python3.8/site-packages/sphinxcontrib/devhelp/__init__.py
#   sphinxcontrib.htmlhelp (2.0.0) from /usr/lib/python3.8/site-packages/sphinxcontrib/htmlhelp/__init__.py
#   sphinxcontrib.serializinghtml (1.1.5) from /usr/lib/python3.8/site-packages/sphinxcontrib/serializinghtml/__init__.py
#   sphinxcontrib.qthelp (1.0.3) from /usr/lib/python3.8/site-packages/sphinxcontrib/qthelp/__init__.py
#   alabaster (0.7.12) from /usr/lib/python3.8/site-packages/alabaster/__init__.py
#   sphinx.ext.autodoc.preserve_defaults (1.0) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/preserve_defaults.py
#   sphinx.ext.autodoc.type_comment (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/type_comment.py
#   sphinx.ext.autodoc (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autodoc/__init__.py
#   sphinx.ext.napoleon (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/napoleon/__init__.py
#   sphinx.ext.viewcode (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/viewcode.py
#   sphinx.ext.autosummary (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/autosummary/__init__.py
#   sphinx.ext.doctest (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/doctest.py
#   sphinx.ext.intersphinx (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/intersphinx.py
#   sphinx.ext.todo (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/todo.py
#   sphinx.ext.coverage (5.0.2) from /usr/lib/python3.8/site-packages/sphinx/ext/coverage.py
#   sphinx_gallery.gen_gallery (0.10.1) from /home/tkloczko/rpmbuild/BUILD/sphinx-gallery-0.10.1/sphinx_gallery/gen_gallery.py
Traceback (most recent call last):
  File "/usr/lib/python3.8/site-packages/sphinx/cmd/build.py", line 276, in build_main
    app.build(args.force_all, filenames)
  File "/usr/lib/python3.8/site-packages/sphinx/application.py", line 329, in build
    self.builder.build_update()
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 285, in build_update
    self.build(['__all__'], to_build)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/__init__.py", line 352, in build
    self.write(docnames, list(updated_docnames), method)
  File "/usr/lib/python3.8/site-packages/sphinx/util/__init__.py", line 517, in wrapper
    return f(*args, **kwargs)
  File "/usr/lib/python3.8/site-packages/sphinx/builders/manpage.py", line 98, in write
    docwriter.write(largetree, destination)
  File "/usr/lib/python3.8/site-packages/docutils/writers/__init__.py", line 78, in write
    self.translate()
  File "/usr/lib/python3.8/site-packages/sphinx/writers/manpage.py", line 31, in translate
    self.document.walkabout(visitor)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 227, in walkabout
    if child.walkabout(visitor):
  [Previous line repeated 8 more times]
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 240, in walkabout
    visitor.dispatch_departure(self)
  File "/usr/lib/python3.8/site-packages/sphinx/util/docutils.py", line 546, in dispatch_departure
    super().dispatch_departure(node)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 2034, in dispatch_departure
    return method(node)
  File "/usr/lib/python3.8/site-packages/docutils/nodes.py", line 2056, in unknown_departure
    raise NotImplementedError(
NotImplementedError: <class 'sphinx.writers.manpage.ManualPageTranslator'> departing unknown node type: imgsgnode
```

**Comment by larsoner** [comment]
Is it necessary to build out of the source tree?

I think the removal of the `'.'` path is making it somehow mess up the `imgsgnode` because that comes from
```
sphinx_gallery/directives.py:class imgsgnode(nodes.General, nodes.Element):
```

**Comment by kloczek** [comment]
Quote from gawk info page "Socumentation is like sex. When it is good it is very good. When it is bad it is better than nothing",
Yes it is necessary to include with every possible ptthon modules documentation.
```
[tkloczko@devel-g2v SPECS]$ ls -1 python-*spec| wc -l; grep %sphinx_build_man python-*spec |wc -l
988
463
```
As you see in case of packages on which I'm working almost half packaged python modules provides sphinx generated documentation as man page.

**Comment by larsoner** [comment]
Yes I understand and agree documentation is important. I mean why is it necessary in your case to build it *outside the source tree*?

**Comment by kloczek** [comment]
Command which i on top of the copied log has been executed in source tree root direcory.

**Comment by Borda** [comment]
@larsoner regarding the actual version is 0.15, this can be closed...

**Comment by larsoner** [comment]
This one I'll close as a dup of #976 since we have a clearer handle on the issue over there

**Comment by larsoner** [comment]
Whoops I meant a dup of #1285
